// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Machines.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20240829192409_Machine")]
    partial class Machine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Machines.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Calidad")
                        .HasColumnType("float");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Deriva")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Evaporacion")
                        .HasColumnType("float");

                    b.Property<string>("Humedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HumedadGrano")
                        .HasColumnType("float");

                    b.Property<bool>("Moving")
                        .HasColumnType("bit");

                    b.Property<string>("Presion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoPorHectarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RindeHumedo")
                        .HasColumnType("float");

                    b.Property<double?>("RindeSeco")
                        .HasColumnType("float");

                    b.Property<double?>("Taponamiento")
                        .HasColumnType("float");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Velocidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelocidadViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ancho = "3.5m",
                            BateriaInterna = "80%",
                            BateriaVehiculo = "90%",
                            Company = "Empresa A",
                            Cultivo = "Trigo",
                            Description = "Cosechadora A",
                            DireccionViento = "Noreste",
                            Humedad = "50%",
                            HumedadGrano = 12.5,
                            Moving = true,
                            Presion = "2.5 bar",
                            ProductoPorHectarea = "100 kg/ha",
                            RindeHumedo = 8.3000000000000007,
                            RindeSeco = 7.0,
                            Temperatura = "22°C",
                            Type = "Cosechadora",
                            Velocidad = "10 km/h",
                            VelocidadViento = "10 km/h"
                        },
                        new
                        {
                            Id = 2,
                            Ancho = "4.0m",
                            BateriaInterna = "75%",
                            BateriaVehiculo = "85%",
                            Company = "Empresa B",
                            Cultivo = "Maíz",
                            Description = "Cosechadora B",
                            DireccionViento = "Oeste",
                            Humedad = "60%",
                            HumedadGrano = 13.0,
                            Moving = false,
                            Presion = "3.0 bar",
                            ProductoPorHectarea = "110 kg/ha",
                            RindeHumedo = 9.0,
                            RindeSeco = 7.5,
                            Temperatura = "25°C",
                            Type = "Cosechadora",
                            Velocidad = "12 km/h",
                            VelocidadViento = "15 km/h"
                        },
                        new
                        {
                            Id = 3,
                            Ancho = "4.5m",
                            BateriaInterna = "85%",
                            BateriaVehiculo = "95%",
                            Company = "Empresa C",
                            Cultivo = "Soja",
                            Description = "Cosechadora C",
                            DireccionViento = "Sureste",
                            Humedad = "55%",
                            HumedadGrano = 14.199999999999999,
                            Moving = true,
                            Presion = "3.5 bar",
                            ProductoPorHectarea = "120 kg/ha",
                            RindeHumedo = 10.0,
                            RindeSeco = 8.0,
                            Temperatura = "20°C",
                            Type = "Cosechadora",
                            Velocidad = "15 km/h",
                            VelocidadViento = "12 km/h"
                        },
                        new
                        {
                            Id = 4,
                            Ancho = "6.0m",
                            BateriaInterna = "90%",
                            BateriaVehiculo = "85%",
                            Calidad = 8.5,
                            Company = "Empresa D",
                            Deriva = 2.5,
                            Description = "Pulverizadora A",
                            DireccionViento = "Noroeste",
                            Evaporacion = 5.0,
                            Humedad = "40%",
                            Moving = true,
                            Presion = "1.8 bar",
                            ProductoPorHectarea = "150 kg/ha",
                            Taponamiento = 1.2,
                            Temperatura = "28°C",
                            Type = "Pulverizadora",
                            Velocidad = "20 km/h",
                            VelocidadViento = "8 km/h"
                        },
                        new
                        {
                            Id = 5,
                            Ancho = "7.0m",
                            BateriaInterna = "88%",
                            BateriaVehiculo = "80%",
                            Calidad = 9.0,
                            Company = "Empresa E",
                            Deriva = 2.7000000000000002,
                            Description = "Pulverizadora B",
                            DireccionViento = "Este",
                            Evaporacion = 4.7999999999999998,
                            Humedad = "45%",
                            Moving = false,
                            Presion = "2.0 bar",
                            ProductoPorHectarea = "160 kg/ha",
                            Taponamiento = 1.5,
                            Temperatura = "30°C",
                            Type = "Pulverizadora",
                            Velocidad = "25 km/h",
                            VelocidadViento = "5 km/h"
                        },
                        new
                        {
                            Id = 6,
                            Ancho = "8.0m",
                            BateriaInterna = "92%",
                            BateriaVehiculo = "87%",
                            Calidad = 9.5,
                            Company = "Empresa F",
                            Deriva = 2.2999999999999998,
                            Description = "Pulverizadora C",
                            DireccionViento = "Sur",
                            Evaporacion = 4.5,
                            Humedad = "50%",
                            Moving = true,
                            Presion = "2.2 bar",
                            ProductoPorHectarea = "170 kg/ha",
                            Taponamiento = 1.0,
                            Temperatura = "26°C",
                            Type = "Pulverizadora",
                            Velocidad = "30 km/h",
                            VelocidadViento = "6 km/h"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
