// <auto-generated />
using System;
using Machines.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Machines.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20240829143429_agregando-MachineData")]
    partial class agregandoMachineData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Machines.Models.ClimaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Humedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelocidadViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineDataId")
                        .IsUnique();

                    b.ToTable("ClimaData");
                });

            modelBuilder.Entity("Machines.Models.GeneralData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineDataId")
                        .IsUnique();

                    b.ToTable("GeneralData");
                });

            modelBuilder.Entity("Machines.Models.Indicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calidad")
                        .HasColumnType("float");

                    b.Property<string>("Cultivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Deriva")
                        .HasColumnType("float");

                    b.Property<double>("Evaporacion")
                        .HasColumnType("float");

                    b.Property<double>("HumedadGrano")
                        .HasColumnType("float");

                    b.Property<int?>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<double>("RindeHumedo")
                        .HasColumnType("float");

                    b.Property<double>("RindeSeco")
                        .HasColumnType("float");

                    b.Property<double>("Taponamiento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calidad = 95.5,
                            Cultivo = "Maíz",
                            Deriva = 1.0,
                            Evaporacion = 2.1000000000000001,
                            HumedadGrano = 12.5,
                            MachineId = 1,
                            RindeHumedo = 20.5,
                            RindeSeco = 18.0,
                            Taponamiento = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Calidad = 97.0,
                            Cultivo = "Trigo",
                            Deriva = 0.5,
                            Evaporacion = 1.8,
                            HumedadGrano = 11.0,
                            MachineId = 2,
                            RindeHumedo = 22.0,
                            RindeSeco = 19.5,
                            Taponamiento = 0.0
                        });
                });

            modelBuilder.Entity("Machines.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Moving")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasDiscriminator<string>("MachineType").HasValue("Machine");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "FarmCo",
                            Description = "Harvesting Machine A",
                            Moving = true,
                            Type = "Cosechadora"
                        },
                        new
                        {
                            Id = 2,
                            Company = "AgriTech",
                            Description = "Spraying Machine B",
                            Moving = false,
                            Type = "Pulverizadora"
                        });
                });

            modelBuilder.Entity("Machines.Models.MachineData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("MachineData");
                });

            modelBuilder.Entity("Machines.Models.OperacionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<string>("Presion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoPorHectarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Velocidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineDataId")
                        .IsUnique();

                    b.ToTable("OperacionData");
                });

            modelBuilder.Entity("Machines.Models.Cosechadora", b =>
                {
                    b.HasBaseType("Machines.Models.Machine");

                    b.Property<string>("Cultivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HumedadGrano")
                        .HasColumnType("float");

                    b.Property<double>("RindeHumedo")
                        .HasColumnType("float");

                    b.Property<double>("RindeSeco")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Cosechadora");
                });

            modelBuilder.Entity("Machines.Models.Pulverizadora", b =>
                {
                    b.HasBaseType("Machines.Models.Machine");

                    b.Property<double>("Calidad")
                        .HasColumnType("float");

                    b.Property<double>("Deriva")
                        .HasColumnType("float");

                    b.Property<double>("Evaporacion")
                        .HasColumnType("float");

                    b.Property<double>("Taponamiento")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Pulverizadora");
                });

            modelBuilder.Entity("Machines.Models.ClimaData", b =>
                {
                    b.HasOne("Machines.Models.MachineData", null)
                        .WithOne("Clima")
                        .HasForeignKey("Machines.Models.ClimaData", "MachineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Machines.Models.GeneralData", b =>
                {
                    b.HasOne("Machines.Models.MachineData", null)
                        .WithOne("General")
                        .HasForeignKey("Machines.Models.GeneralData", "MachineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Machines.Models.MachineData", b =>
                {
                    b.HasOne("Machines.Models.Machine", null)
                        .WithOne("Data")
                        .HasForeignKey("Machines.Models.MachineData", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Machines.Models.OperacionData", b =>
                {
                    b.HasOne("Machines.Models.MachineData", null)
                        .WithOne("Operacion")
                        .HasForeignKey("Machines.Models.OperacionData", "MachineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Machines.Models.Machine", b =>
                {
                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Machines.Models.MachineData", b =>
                {
                    b.Navigation("Clima")
                        .IsRequired();

                    b.Navigation("General")
                        .IsRequired();

                    b.Navigation("Operacion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
