// <auto-generated />
using Machines.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Machines.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20240829185037_simplificacion-Modelos")]
    partial class simplificacionModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Machines.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Humedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Moving")
                        .HasColumnType("bit");

                    b.Property<string>("Presion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoPorHectarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Velocidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelocidadViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasDiscriminator<string>("MachineType").HasValue("Machine");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Machines.Models.Cosechadora", b =>
                {
                    b.HasBaseType("Machines.Models.Machine");

                    b.Property<string>("Cultivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HumedadGrano")
                        .HasColumnType("float");

                    b.Property<double>("RindeHumedo")
                        .HasColumnType("float");

                    b.Property<double>("RindeSeco")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Cosechadora");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ancho = "3.5m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "FarmCo",
                            Description = "Cosechadora A",
                            DireccionViento = "Norte",
                            Humedad = "60%",
                            Moving = true,
                            Presion = "5 bar",
                            ProductoPorHectarea = "150 kg",
                            Temperatura = "25°C",
                            Type = "Cosechadora",
                            Velocidad = "20 km/h",
                            VelocidadViento = "10 km/h",
                            Cultivo = "Maíz",
                            HumedadGrano = 12.5,
                            RindeHumedo = 20.5,
                            RindeSeco = 18.0
                        },
                        new
                        {
                            Id = 2,
                            Ancho = "3.0m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "AgriCorp",
                            Description = "Cosechadora B",
                            DireccionViento = "Oeste",
                            Humedad = "55%",
                            Moving = false,
                            Presion = "6 bar",
                            ProductoPorHectarea = "100 kg",
                            Temperatura = "22°C",
                            Type = "Cosechadora",
                            Velocidad = "25 km/h",
                            VelocidadViento = "8 km/h",
                            Cultivo = "Trigo",
                            HumedadGrano = 13.0,
                            RindeHumedo = 22.0,
                            RindeSeco = 19.5
                        },
                        new
                        {
                            Id = 3,
                            Ancho = "3.8m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "HarvestMax",
                            Description = "Cosechadora C",
                            DireccionViento = "Sur",
                            Humedad = "50%",
                            Moving = true,
                            Presion = "5.5 bar",
                            ProductoPorHectarea = "140 kg",
                            Temperatura = "20°C",
                            Type = "Cosechadora",
                            Velocidad = "22 km/h",
                            VelocidadViento = "12 km/h",
                            Cultivo = "Soja",
                            HumedadGrano = 11.800000000000001,
                            RindeHumedo = 21.0,
                            RindeSeco = 18.800000000000001
                        });
                });

            modelBuilder.Entity("Machines.Models.Pulverizadora", b =>
                {
                    b.HasBaseType("Machines.Models.Machine");

                    b.Property<double>("Calidad")
                        .HasColumnType("float");

                    b.Property<double>("Deriva")
                        .HasColumnType("float");

                    b.Property<double>("Evaporacion")
                        .HasColumnType("float");

                    b.Property<double>("Taponamiento")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Pulverizadora");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Ancho = "3.2m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "AgriTech",
                            Description = "Pulverizadora A",
                            DireccionViento = "Este",
                            Humedad = "58%",
                            Moving = false,
                            Presion = "4.5 bar",
                            ProductoPorHectarea = "120 kg",
                            Temperatura = "24°C",
                            Type = "Pulverizadora",
                            Velocidad = "18 km/h",
                            VelocidadViento = "15 km/h",
                            Calidad = 95.0,
                            Deriva = 0.69999999999999996,
                            Evaporacion = 1.2,
                            Taponamiento = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Ancho = "3.5m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "SprayMaster",
                            Description = "Pulverizadora B",
                            DireccionViento = "Noroeste",
                            Humedad = "62%",
                            Moving = true,
                            Presion = "4.8 bar",
                            ProductoPorHectarea = "130 kg",
                            Temperatura = "26°C",
                            Type = "Pulverizadora",
                            Velocidad = "19 km/h",
                            VelocidadViento = "9 km/h",
                            Calidad = 96.0,
                            Deriva = 0.40000000000000002,
                            Evaporacion = 1.5,
                            Taponamiento = 0.20000000000000001
                        },
                        new
                        {
                            Id = 6,
                            Ancho = "3.1m",
                            BateriaInterna = "12V",
                            BateriaVehiculo = "24V",
                            Company = "FieldSpray",
                            Description = "Pulverizadora C",
                            DireccionViento = "Sureste",
                            Humedad = "57%",
                            Moving = true,
                            Presion = "5.0 bar",
                            ProductoPorHectarea = "140 kg",
                            Temperatura = "23°C",
                            Type = "Pulverizadora",
                            Velocidad = "20 km/h",
                            VelocidadViento = "12 km/h",
                            Calidad = 94.0,
                            Deriva = 0.59999999999999998,
                            Evaporacion = 1.0,
                            Taponamiento = 0.29999999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
