// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Machines.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20240829202114_examples-seeds")]
    partial class examplesseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Machines.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BateriaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Calidad")
                        .HasColumnType("float");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Deriva")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Evaporacion")
                        .HasColumnType("float");

                    b.Property<string>("Humedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HumedadGrano")
                        .HasColumnType("float");

                    b.Property<bool>("Moving")
                        .HasColumnType("bit");

                    b.Property<string>("Presion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoPorHectarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RindeHumedo")
                        .HasColumnType("float");

                    b.Property<double?>("RindeSeco")
                        .HasColumnType("float");

                    b.Property<double?>("Taponamiento")
                        .HasColumnType("float");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Velocidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelocidadViento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ancho = "3.5m",
                            BateriaInterna = "80%",
                            BateriaVehiculo = "90%",
                            Company = "Empresa A",
                            Cultivo = "Trigo",
                            Description = "Cosechadora A",
                            DireccionViento = "Noreste",
                            Humedad = "50%",
                            HumedadGrano = 12.5,
                            Moving = true,
                            Presion = "2.5 bar",
                            ProductoPorHectarea = "100 kg/ha",
                            RindeHumedo = 8.3000000000000007,
                            RindeSeco = 7.0,
                            Temperatura = "22°C",
                            Type = "Cosechadora",
                            Velocidad = "10 km/h",
                            VelocidadViento = "10 km/h"
                        },
                        new
                        {
                            Id = 3,
                            Ancho = "4.5m",
                            BateriaInterna = "85%",
                            BateriaVehiculo = "95%",
                            Company = "Empresa C",
                            Cultivo = "Soja",
                            Description = "Cosechadora C",
                            DireccionViento = "Sureste",
                            Humedad = "55%",
                            HumedadGrano = 14.199999999999999,
                            Moving = true,
                            Presion = "3.5 bar",
                            ProductoPorHectarea = "120 kg/ha",
                            RindeHumedo = 10.0,
                            RindeSeco = 8.0,
                            Temperatura = "20°C",
                            Type = "Cosechadora",
                            Velocidad = "15 km/h",
                            VelocidadViento = "12 km/h"
                        },
                        new
                        {
                            Id = 5,
                            Ancho = "3.8m",
                            BateriaInterna = "77%",
                            BateriaVehiculo = "83%",
                            Company = "Empresa E",
                            Cultivo = "Avena",
                            Description = "Cosechadora E",
                            DireccionViento = "Sur",
                            Humedad = "65%",
                            HumedadGrano = 13.800000000000001,
                            Moving = false,
                            Presion = "2.8 bar",
                            ProductoPorHectarea = "110 kg/ha",
                            RindeHumedo = 9.1999999999999993,
                            RindeSeco = 7.7999999999999998,
                            Temperatura = "24°C",
                            Type = "Cosechadora",
                            Velocidad = "11 km/h",
                            VelocidadViento = "14 km/h"
                        },
                        new
                        {
                            Id = 7,
                            Ancho = "4.0m",
                            BateriaInterna = "82%",
                            BateriaVehiculo = "88%",
                            Company = "Empresa G",
                            Cultivo = "Cebada",
                            Description = "Cosechadora G",
                            DireccionViento = "Oeste",
                            Humedad = "60%",
                            HumedadGrano = 12.9,
                            Moving = true,
                            Presion = "3.2 bar",
                            ProductoPorHectarea = "105 kg/ha",
                            RindeHumedo = 8.6999999999999993,
                            RindeSeco = 7.2999999999999998,
                            Temperatura = "23°C",
                            Type = "Cosechadora",
                            Velocidad = "12 km/h",
                            VelocidadViento = "13 km/h"
                        },
                        new
                        {
                            Id = 9,
                            Ancho = "4.2m",
                            BateriaInterna = "90%",
                            BateriaVehiculo = "80%",
                            Company = "Empresa I",
                            Cultivo = "Maíz",
                            Description = "Cosechadora I",
                            DireccionViento = "Noroeste",
                            Humedad = "50%",
                            HumedadGrano = 14.0,
                            Moving = false,
                            Presion = "3.0 bar",
                            ProductoPorHectarea = "115 kg/ha",
                            RindeHumedo = 9.5,
                            RindeSeco = 7.5999999999999996,
                            Temperatura = "26°C",
                            Type = "Cosechadora",
                            Velocidad = "13 km/h",
                            VelocidadViento = "11 km/h"
                        },
                        new
                        {
                            Id = 11,
                            Ancho = "3.7m",
                            BateriaInterna = "85%",
                            BateriaVehiculo = "92%",
                            Company = "Empresa K",
                            Cultivo = "Trigo",
                            Description = "Cosechadora K",
                            DireccionViento = "Noreste",
                            Humedad = "53%",
                            HumedadGrano = 12.199999999999999,
                            Moving = true,
                            Presion = "2.7 bar",
                            ProductoPorHectarea = "100 kg/ha",
                            RindeHumedo = 8.0,
                            RindeSeco = 7.2000000000000002,
                            Temperatura = "21°C",
                            Type = "Cosechadora",
                            Velocidad = "11 km/h",
                            VelocidadViento = "10 km/h"
                        },
                        new
                        {
                            Id = 2,
                            Ancho = "7.0m",
                            BateriaInterna = "88%",
                            BateriaVehiculo = "80%",
                            Calidad = 90.0,
                            Company = "Empresa E",
                            Deriva = 2.7000000000000002,
                            Description = "Pulverizadora B",
                            DireccionViento = "Este",
                            Evaporacion = 4.7999999999999998,
                            Humedad = "45%",
                            Moving = false,
                            Presion = "2.0 bar",
                            ProductoPorHectarea = "160 kg/ha",
                            Taponamiento = 1.5,
                            Temperatura = "30°C",
                            Type = "Pulverizadora",
                            Velocidad = "25 km/h",
                            VelocidadViento = "5 km/h"
                        },
                        new
                        {
                            Id = 4,
                            Ancho = "6.0m",
                            BateriaInterna = "90%",
                            BateriaVehiculo = "85%",
                            Calidad = 85.0,
                            Company = "Empresa D",
                            Deriva = 2.5,
                            Description = "Pulverizadora A",
                            DireccionViento = "Noroeste",
                            Evaporacion = 5.0,
                            Humedad = "40%",
                            Moving = true,
                            Presion = "1.8 bar",
                            ProductoPorHectarea = "150 kg/ha",
                            Taponamiento = 1.2,
                            Temperatura = "28°C",
                            Type = "Pulverizadora",
                            Velocidad = "20 km/h",
                            VelocidadViento = "8 km/h"
                        },
                        new
                        {
                            Id = 6,
                            Ancho = "8.0m",
                            BateriaInterna = "92%",
                            BateriaVehiculo = "87%",
                            Calidad = 95.0,
                            Company = "Empresa F",
                            Deriva = 2.2999999999999998,
                            Description = "Pulverizadora C",
                            DireccionViento = "Sur",
                            Evaporacion = 4.5,
                            Humedad = "50%",
                            Moving = true,
                            Presion = "2.2 bar",
                            ProductoPorHectarea = "170 kg/ha",
                            Taponamiento = 1.0,
                            Temperatura = "26°C",
                            Type = "Pulverizadora",
                            Velocidad = "30 km/h",
                            VelocidadViento = "6 km/h"
                        },
                        new
                        {
                            Id = 8,
                            Ancho = "6.5m",
                            BateriaInterna = "87%",
                            BateriaVehiculo = "84%",
                            Calidad = 88.0,
                            Company = "Empresa G",
                            Deriva = 2.6000000000000001,
                            Description = "Pulverizadora D",
                            DireccionViento = "Suroeste",
                            Evaporacion = 4.5999999999999996,
                            Humedad = "48%",
                            Moving = false,
                            Presion = "1.9 bar",
                            ProductoPorHectarea = "155 kg/ha",
                            Taponamiento = 1.3,
                            Temperatura = "27°C",
                            Type = "Pulverizadora",
                            Velocidad = "22 km/h",
                            VelocidadViento = "7 km/h"
                        },
                        new
                        {
                            Id = 10,
                            Ancho = "7.5m",
                            BateriaInterna = "85%",
                            BateriaVehiculo = "80%",
                            Calidad = 90.0,
                            Company = "Empresa H",
                            Deriva = 2.3999999999999999,
                            Description = "Pulverizadora E",
                            DireccionViento = "Oeste",
                            Evaporacion = 4.7000000000000002,
                            Humedad = "42%",
                            Moving = true,
                            Presion = "2.1 bar",
                            ProductoPorHectarea = "165 kg/ha",
                            Taponamiento = 1.3999999999999999,
                            Temperatura = "29°C",
                            Type = "Pulverizadora",
                            Velocidad = "24 km/h",
                            VelocidadViento = "6 km/h"
                        },
                        new
                        {
                            Id = 12,
                            Ancho = "6.8m",
                            BateriaInterna = "88%",
                            BateriaVehiculo = "82%",
                            Calidad = 89.0,
                            Company = "Empresa J",
                            Deriva = 2.5,
                            Description = "Pulverizadora F",
                            DireccionViento = "Norte",
                            Evaporacion = 4.9000000000000004,
                            Humedad = "55%",
                            Moving = false,
                            Presion = "2.3 bar",
                            ProductoPorHectarea = "160 kg/ha",
                            Taponamiento = 1.6000000000000001,
                            Temperatura = "25°C",
                            Type = "Pulverizadora",
                            Velocidad = "23 km/h",
                            VelocidadViento = "5 km/h"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
